env:
  browser: true
  es2021: true
  jest: true
extends:
  - react-app
  - react-app/jest
  - plugin:react/recommended
  - xo
overrides:
  - extends:
      - xo-typescript
    files:
      - '*.ts'
      - '*.tsx'
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
      jsx: true
plugins:
  - react
rules: {}
